services:
  sgre-db:
    image: postgis/postgis:17-3.5
    container_name: sgre-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: sgre
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/docker_data/db/data:/var/lib/postgresql/data

  sgre-pgadmin4:
    image: dpage/pgadmin4:9
    container_name: sgre-pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
      PGADMIN_LISTEN_PORT: 5050
    ports:
    - "127.0.0.1:5050:5050"
    volumes:
    - ~/docker_data/pgadmin/pgadmin:/var/lib/pgadmin